version: "3"
services:
  pythonathon:
#    image: pythonathon:latest
    build: pythonathon_v3
    environment:
      DEBUGMODE: 1
      PASSWORD_FILE: /secrets/db_password
      JUPYTERHUB_HOST: jupyterhub
      JUPYTERHUB_PORT: 8000
      JUPYTERHUB_PATH: /notebook/
    volumes:
      - "./secrets:/secrets:ro"
    depends_on:
      - db
    deploy:
      replicas: 1
      restart_policy:
        condition: any
        window: 5s
    networks:
      - ctfnet

  db:
    build: db
    environment:
      POSTGRES_PASSWORD_FILE: /secrets/db_password
      POSTGRES_DB: pythonathon
      POSTGRES_MULTIPLE_DATABASES: jupyterhub
      PGDATA: /persistent/postgres/data
      NETWORK_ACCESS: internal
    volumes:
      - "./secrets:/secrets:ro"
      - "./db_data:/persistent/postgres/data"
    deploy:
      replicas: 1
      restart_policy:
        condition: any
        window: 5s
    networks:
      - ctfnet
    healthcheck:
      test: ["CMD", "psql", "-h", "localhost", "-p", "5432"]

  jupyterhub:
#    image: jupyterhub/jupyterhub
    build: jupyterhub
    networks:
      - ctfnet
    environment:
      OAUTH2_TOKEN_URL: http://pythonathon/o/token
      OAUTH2_AUTHORIZE_URL: http://pythonathon/o/authorize
      POSTGRES_HOST: db
      POSTGRES_DB: jupyterhub
      POSTGRES_PASSWORD_FILE: "/secrets/db_password"
      ADMINS: "scnerd"
      JUPYTERHUB_PATH: /notebook/
    volumes:
      - "./secrets:/secrets:ro"

  proxy:
    build: proxy
    networks:
      - webnet
      - ctfnet
    ports:
      - 0.0.0.0:8000:8000  # debug, direct access
    environment:
      VIRTUAL_HOST: pythonathon.davidmaxson.name
      LETSENCRYPT_HOST: pythonathon.davidmaxson.name
      LETSENCRYPT_EMAIL: scnerd@gmail.com
      MAIN_HOST: pythonathon
      MAIN_PORT: 3031
      HUB_HOST: jupyterhub
      HUB_PORT: 8000
      HUB_PATH: /notebook/
    depends_on:
      - pythonathon


networks:
  ctfnet:
  webnet:
    external:
      name: webnet
