version: "3"
services:
  pythonathon:
#    image: pythonathon:latest
    build: pythonathon_v3
    ports:
      - 127.0.0.1:8000:8000
    environment:
      DEBUGMODE: 1
      PASSWORD_FILE: /secrets/db_password
      VIRTUAL_HOST: pythonathon.davidmaxson.name
      LETSENCRYPT_HOST: pythonathon.davidmaxson.name
      LETSENCRYPT_EMAIL: scnerd@gmail.com
      JUPYTERHUB_HOST: jupyterhub
    volumes:
      - "./secrets:/secrets:ro"
    depends_on:
      - db
    deploy:
      replicas: 1
      restart_policy:
        condition: any
        window: 5s
    networks:
      - ctfnet
      - webnet

  db:
    image: "postgres:alpine"
    environment:
      POSTGRES_PASSWORD_FILE: /secrets/db_password
      POSTGRES_DB: pythonathon
      PGDATA: /persistent/postgres/data
      NETWORK_ACCESS: internal
    volumes:
      - "./secrets:/secrets:ro"
      - "./db_data:/persistent/postgres/data"
    deploy:
      replicas: 1
      restart_policy:
        condition: any
        window: 5s
    networks:
      - ctfnet
    healthcheck:
      test: ["CMD", "psql", "-h", "localhost", "-p", "5432"]

  jupyterhub:
    image: jupyterhub/jupyterhub

networks:
  ctfnet:
  webnet:
    external:
      name: webnet

