version: '3'
services:
  pythonathon:
    build: pythonathon_v3
    environment:
      DEBUGMODE: 0
  jupyterhub:
    environment:
      OAUTH2_TOKEN_URL: https://pythonathon.davidmaxson.name/o/token
      OAUTH2_AUTHORIZE_URL: https://pythonathon.davidmaxson.name/o/authorize
      OAUTH_CALLBACK_URL: https://pythonathon.davidmaxson.name/notebook/hub/oauth_callback